travis:
  secure:
    BINSTAR_TOKEN: fdW8XKA8eepfreR0Yt7cll+Ux0+smZbolqRsBSYiFac0xNJjdCwJvutSuWNnftoD1d0mKjS2uMz4SBHBq/y5WvZWw7078lzcxWoW4o0/Izg1goXcCt8GCGOk0zB6S1zX1oFTMNhdSyD48NXApi5o5NzicLJKiKS75m5WVsM7QxaBM0Rc4dWUDP8ygjbx/N4pqR0fkqOp+FR7oTkvqLjHDyJe/dl/JzWuAcjuHLgAFhlqvfO75Swxwso9N0PbkBEV6A8HPmN2laAjzUC3X7oBOY4Ki0X3RCUHuWzBn9bewuG1ueQKH9JvU5CthENuroWLbBghOhrh48LRhU68gwHZ8H+s6Zl4+q3NMiSNT3JSP1pw6qqpKi3bI9YlmpqHtkw4UBw+iY2wp0tnCkwNvMEIv8YUidIRJ3FHsDRCo7ZXRNiJTpZV5EzVFRyQIVvgNzNtx0mmk+u18aoRtQHuLWLN7IzHkLO96Vo4IJGtOP+VvBA8Odo2IWTwFKMhys30NNoH+hkgRXe+DcmrUVDBHmZW5wu8OHkTJ0XfqnDXDXJY2yaMI3/h7/kzcZ16BtGVO2kwvta/+gXfAfOPqOI4nPZ4dAHSyfr5KMpYqIAQNckdFz/IqL8VFz9K+JhfnsNEpod/ORA+lnqC6TXikhiR1NSSlKBJIUPSPqmiVvrhljw5V3I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
